import { useMemo, useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import { CalendarDays, ExternalLink, Map, RefreshCw, Thermometer, Waves } from 'lucide-react';
import { FeaturePageLayout } from '@/components/FeaturePageLayout';
import { CitySearch } from '@/components/CitySearch';
import { EnvironmentalMap, type EnvironmentalPath, type EnvironmentalPoint } from '@/components/EnvironmentalMap';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { fetchHistoricalDailyWeather, fetchThirtyYearMonthlyBaseline } from '@/lib/environmentalLayers';
import { getRegionLabel } from '@/lib/globalWeather';
import { fetchFloodStormArchive } from '@/lib/eonet';
import type { CitySearchResult } from '@/lib/openMeteo';

const JAKARTA = { lat: -6.2088, lng: 106.8456 };
const dateDaysAgo = (days: number) => { const date = new Date(); date.setUTCDate(date.getUTCDate() - days); return date.toISOString().slice(0, 10); };
const dayLabel = (date: string) => new Date(`${date}T12:00:00Z`).toLocaleDateString(undefined, { month: 'short', day: 'numeric', timeZone: 'UTC' });

const HistoryPage = () => {
  const [place, setPlace] = useState<CitySearchResult | null>(null);
  const [windowDays, setWindowDays] = useState(30);
  const [selectedDate, setSelectedDate] = useState(() => dateDaysAgo(7));
  const [selectedEventId, setSelectedEventId] = useState('');
  const [replayIndex, setReplayIndex] = useState(0);
  const lat = place?.lat ?? JAKARTA.lat, lng = place?.lng ?? JAKARTA.lng;
  const regionLabel = place ? getRegionLabel(place) : 'Jakarta, Indonesia';
  const startDate = dateDaysAgo(windowDays + 7), endDate = dateDaysAgo(7);
  const historyQuery = useQuery({ queryKey: ['historical-daily-weather', lat, lng, startDate, endDate], queryFn: () => fetchHistoricalDailyWeather(lat, lng, startDate, endDate), staleTime: 12 * 60 * 60 * 1000, retry: 1 });
  const month = Number(selectedDate.slice(5, 7)) || new Date().getUTCMonth() + 1;
  const baselineQuery = useQuery({ queryKey: ['climate-monthly-baseline-1991-2020', lat, lng, month], queryFn: () => fetchThirtyYearMonthlyBaseline(lat, lng, month), staleTime: 30 * 24 * 60 * 60 * 1000, retry: 1 });
  const eventQuery = useQuery({ queryKey: ['eonet-flood-storm-archive'], queryFn: fetchFloodStormArchive, staleTime: 60 * 60 * 1000, retry: 1 });
  const days = useMemo(() => historyQuery.data ?? [], [historyQuery.data]);
  const chosenWindow = useMemo(() => days.slice(-windowDays), [days, windowDays]);
  const selected = days.find((day) => day.date === selectedDate) ?? days.at(-1) ?? null;
  const maxRain = Math.max(1, ...days.map((day) => day.rainMm ?? 0));
  const validTemps = days.map((day) => day.temperatureMeanC).filter((value): value is number => value !== null);
  const minTemp = Math.min(0, ...validTemps), maxTemp = Math.max(minTemp + 1, ...validTemps);
  const events = eventQuery.data ?? [];
  const selectedEvent = events.find((event) => event.id === selectedEventId) ?? events[0] ?? null;
  const track = selectedEvent?.track ?? [];
  const frameIndex = Math.max(0, Math.min(replayIndex, Math.max(0, track.length - 1)));
  const frame = track[frameIndex] ?? null;
  const eventPoints: EnvironmentalPoint[] = selectedEvent ? [
    ...(track.length > 1 ? [{ id: `${selectedEvent.id}-start`, lat: track[0].lat, lng: track[0].lng, label: 'Event path starts', color: '#60a5fa', radius: 5 }] : []),
    { id: `${selectedEvent.id}-frame`, lat: frame?.lat ?? selectedEvent.lat, lng: frame?.lng ?? selectedEvent.lng, label: selectedEvent.title, detail: frame?.date ? `Source geometry date: ${frame.date}` : selectedEvent.date, color: '#f59e0b', radius: 8 },
  ] : [];
  const visibleTrack = track.slice(0, frameIndex + 1);
  const eventPaths: EnvironmentalPath[] = selectedEvent && visibleTrack.length > 1 ? [{ id: selectedEvent.id, positions: visibleTrack.map((item) => [item.lat, item.lng]), color: '#f59e0b', label: selectedEvent.title }] : [];

  return <FeaturePageLayout eyebrow="History & climate" title="Explore past weather & climate" description="Move through recent daily weather for a selected city, compare it with long-term monthly averages, and replay documented event positions where the source provides them.">
    <div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><h2 className="text-lg font-semibold">Recent weather timeline</h2><p className="text-sm text-muted-foreground">{regionLabel} · daily archive values</p></div><div className="flex w-full flex-col gap-2 sm:w-auto sm:flex-row"><CitySearch onSelect={setPlace} onReset={() => setPlace(null)} placeholder="Search a city…" /><select aria-label="Timeline length" className="h-10 rounded-lg border bg-background px-3 text-sm" value={windowDays} onChange={(event) => setWindowDays(Number(event.target.value))}><option value={30}>Past 30 days</option><option value={60}>Past 60 days</option><option value={90}>Past 90 days</option></select><Button variant="outline" size="icon" aria-label="Refresh historic data" onClick={() => void historyQuery.refetch()} disabled={historyQuery.isFetching}><RefreshCw className={`h-4 w-4 ${historyQuery.isFetching ? 'animate-spin' : ''}`} /></Button></div></div>
    {historyQuery.isLoading ? <Card><CardContent className="p-8 text-center text-sm text-muted-foreground">Loading past weather…</CardContent></Card> : historyQuery.isError ? <Card><CardContent className="p-5 text-sm text-muted-foreground">Past weather is temporarily unavailable for this place or date range. Please try again later.</CardContent></Card> : <>
      <Card><CardHeader><CardTitle className="flex items-center gap-2 text-base"><CalendarDays className="h-4 w-4 text-primary" />Select a day</CardTitle><CardDescription>Choose a point in the timeline to see daily details and compare them with the monthly climate average.</CardDescription></CardHeader><CardContent>
        <div className="grid grid-cols-7 gap-2 sm:grid-cols-10 lg:grid-cols-[repeat(15,minmax(0,1fr))]">{chosenWindow.map((day) => { const isSelected = day.date === selectedDate; const intensity = day.rainMm === null ? 0 : Math.max(10, (day.rainMm / maxRain) * 100); return <button type="button" key={day.date} aria-pressed={isSelected} onClick={() => setSelectedDate(day.date)} className={`min-w-0 rounded-xl border p-2 text-center transition ${isSelected ? 'border-primary bg-primary/10 shadow-sm' : 'bg-card hover:border-primary/40'}`}><span className="block text-[10px] text-muted-foreground">{new Date(`${day.date}T12:00:00Z`).toLocaleDateString(undefined, { weekday: 'short', timeZone: 'UTC' })}</span><span className="block text-xs font-semibold">{day.date.slice(8)}</span><span className="mx-auto mt-2 block h-1.5 w-full overflow-hidden rounded-full bg-muted"><span className="block h-full rounded-full bg-sky-500" style={{ width: `${intensity}%` }} /></span><span className="mt-1 block text-[10px] text-muted-foreground">{day.rainMm === null ? '—' : `${day.rainMm.toFixed(0)} mm`}</span></button>; })}</div>
        <div className="mt-5 grid gap-3 sm:grid-cols-2"><div className="flex items-center justify-between rounded-xl border bg-muted/30 p-4"><span className="flex items-center gap-2 text-sm text-muted-foreground"><Thermometer className="h-4 w-4 text-amber-500" />Average temperature</span><strong className="text-lg">{selected?.temperatureMeanC === null || selected?.temperatureMeanC === undefined ? '—' : `${selected.temperatureMeanC.toFixed(1)}°C`}</strong></div><div className="flex items-center justify-between rounded-xl border bg-muted/30 p-4"><span className="flex items-center gap-2 text-sm text-muted-foreground"><Waves className="h-4 w-4 text-sky-500" />Rain that day</span><strong className="text-lg">{selected?.rainMm === null || selected?.rainMm === undefined ? '—' : `${selected.rainMm.toFixed(1)} mm`}</strong></div></div>
        <p className="mt-2 text-xs text-muted-foreground">Selected date: {selectedDate}. Archive values are gridded estimates and may be revised; they are not local rain-gauge readings.</p>
      </CardContent></Card>
      <section className="grid gap-4 lg:grid-cols-[minmax(0,1.2fr)_minmax(280px,0.8fr)]"><Card><CardHeader><CardTitle className="text-base">Daily pattern</CardTitle><CardDescription>Blue bars show daily rain; gold bars show average temperature.</CardDescription></CardHeader><CardContent><div className="max-h-80 space-y-2 overflow-y-auto pr-1">{chosenWindow.map((day) => { const tempWidth = day.temperatureMeanC === null ? 0 : Math.max(5, ((day.temperatureMeanC - minTemp) / (maxTemp - minTemp)) * 25); return <button type="button" key={day.date} onClick={() => setSelectedDate(day.date)} className={`grid w-full grid-cols-[74px_minmax(0,1fr)_52px] items-center gap-3 rounded-lg px-2 py-1.5 text-left text-xs ${day.date === selectedDate ? 'bg-primary/10' : 'hover:bg-muted/50'}`}><span className="text-muted-foreground">{dayLabel(day.date)}</span><span className="flex h-5 items-center gap-1"><span className="block h-2 rounded-full bg-sky-500" style={{ width: `${Math.max(day.rainMm === null ? 0 : 4, (day.rainMm ?? 0) / maxRain * 62)}%` }} /><span className="block h-2 rounded-full bg-amber-400" style={{ width: `${tempWidth}%` }} /></span><span className="text-right font-medium">{day.rainMm === null ? '—' : `${day.rainMm.toFixed(0)} mm`}</span></button>; })}</div></CardContent></Card>
        <Card><CardHeader><CardTitle className="text-base">30-year monthly average</CardTitle><CardDescription>Typical daily weather for {new Date(Date.UTC(2020, month - 1, 1)).toLocaleDateString(undefined, { month: 'long', timeZone: 'UTC' })} ({baselineQuery.data?.years ?? '1991–2020'}).</CardDescription></CardHeader><CardContent>
          {baselineQuery.isLoading ? <p className="text-sm text-muted-foreground">Loading climate average…</p> : baselineQuery.isError ? <p className="text-sm text-muted-foreground">The long-term comparison is temporarily unavailable.</p> : <div className="space-y-3"><div className="rounded-xl border bg-muted/30 p-4"><p className="text-xs text-muted-foreground">Average temperature</p><p className="mt-1 text-2xl font-bold">{baselineQuery.data?.temperatureC?.toFixed(1) ?? '—'}°C</p>{selected?.temperatureMeanC !== null && selected?.temperatureMeanC !== undefined && baselineQuery.data?.temperatureC !== null && <p className="text-xs text-muted-foreground">Selected day: {selected.temperatureMeanC >= baselineQuery.data.temperatureC ? '+' : ''}{(selected.temperatureMeanC - baselineQuery.data.temperatureC).toFixed(1)}°C vs monthly average</p>}</div><div className="rounded-xl border bg-muted/30 p-4"><p className="text-xs text-muted-foreground">Average rain per day</p><p className="mt-1 text-2xl font-bold">{baselineQuery.data?.rainMmPerDay?.toFixed(1) ?? '—'} mm</p>{selected?.rainMm !== null && selected?.rainMm !== undefined && baselineQuery.data?.rainMmPerDay !== null && <p className="text-xs text-muted-foreground">Selected day: {(selected.rainMm - baselineQuery.data.rainMmPerDay).toFixed(1)} mm vs monthly daily average</p>}</div><p className="text-xs text-muted-foreground">Long-term reference: 1991–2020 archive. A monthly average gives context, not a forecast or an official neighborhood climate-normal statement.</p></div>}
        </CardContent></Card></section>
    </>}
    <Card><CardHeader><CardTitle className="flex items-center gap-2 text-base"><Map className="h-4 w-4 text-primary" />Recent flood & severe-storm replay</CardTitle><CardDescription>Replay dated event positions reported by NASA EONET over the past year.</CardDescription></CardHeader><CardContent className="space-y-4">
      {eventQuery.isLoading ? <p className="text-sm text-muted-foreground">Loading documented events…</p> : eventQuery.isError ? <p className="text-sm text-muted-foreground">The event archive is temporarily unavailable. Try again later.</p> : !events.length ? <p className="text-sm text-muted-foreground">No recent events with map geometry are available from the source.</p> : <>
        <div className="flex flex-col gap-3 sm:flex-row"><select aria-label="Select historical event" className="h-10 min-w-0 flex-1 rounded-lg border bg-background px-3 text-sm" value={selectedEvent?.id ?? ''} onChange={(event) => { setSelectedEventId(event.target.value); setReplayIndex(0); }}>{events.map((event) => <option key={event.id} value={event.id}>{event.title} · {event.category}</option>)}</select><a href={selectedEvent?.link || 'https://eonet.gsfc.nasa.gov/'} target="_blank" rel="noreferrer" className="inline-flex h-10 items-center justify-center gap-2 rounded-lg border px-3 text-sm font-medium hover:bg-muted"><ExternalLink className="h-4 w-4" />Source record</a></div>
        {selectedEvent && <><div className="flex flex-wrap items-center justify-between gap-2"><div><p className="font-medium">{selectedEvent.title}</p><p className="text-xs text-muted-foreground">{selectedEvent.category} · {track.length ? `${track.length} dated positions` : 'event location only'} · NASA EONET</p></div><span className="text-xs text-muted-foreground">{frame?.date ?? selectedEvent.date ?? 'Date not supplied'}</span></div><EnvironmentalMap points={eventPoints} paths={eventPaths} center={{ lat: frame?.lat ?? selectedEvent.lat, lng: frame?.lng ?? selectedEvent.lng }} zoom={track.length > 1 ? 4 : 3} height={420} emptyLabel="This source record has no mappable positions." />
          {track.length > 1 ? <div className="space-y-2"><label htmlFor="event-replay" className="flex justify-between text-xs text-muted-foreground"><span>Scrub through source positions</span><span>{frameIndex + 1} of {track.length}</span></label><input id="event-replay" type="range" min={0} max={track.length - 1} value={frameIndex} onChange={(event) => setReplayIndex(Number(event.target.value))} className="w-full accent-amber-500" /><div className="flex justify-between text-[10px] text-muted-foreground"><span>{track[0]?.date}</span><span>{track.at(-1)?.date}</span></div></div> : <p className="text-xs text-muted-foreground">The event feed provides a location, not a sequence of track positions, for this record.</p>}</>}
      </>}
      <div className="rounded-xl border bg-muted/20 p-3 text-xs text-muted-foreground"><p>Event geometry is shown only when NASA provides dated map positions. This feed does not provide event pressure or rainfall totals, so those are not inferred here. For detailed U.S. radar volumes and retrospective storm reports, see the <a className="font-medium text-primary underline" href="https://www.ncei.noaa.gov/products/radar/next-generation-weather-radar" target="_blank" rel="noreferrer">NOAA/NCEI NEXRAD archive</a> and <a className="font-medium text-primary underline" href="https://www.ncei.noaa.gov/access/storm-events-database/" target="_blank" rel="noreferrer">NCEI Storm Events database</a>.</p></div>
    </CardContent></Card>
  </FeaturePageLayout>;
};
export default HistoryPage;
